name: "Tests"
on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'dist/**'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'dist/**'

jobs:
  # test action works running from the graph
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["macos-11", "macos-12"]
        xcode-version: ["13.1", "13.2.1", "13.4"]
        include:
          - operating-system: "macos-10.15"
            xcode-version: "11.0"
          - operating-system: "macos-10.15"
            xcode-version: "11.5"
          - operating-system: "macos-10.15"
            xcode-version: "12.0.1"
          - operating-system: "macos-10.15"
            xcode-version: "12.4"
          - operating-system: "macos-11"
            xcode-version: "12.0.1"
        exclude:
          - operating-system: "macos-11"
            xcode-version: "13.4"
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: bot@sinoru.io
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - run: xcodebuild -version
