name: "Tests"
on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'dist/**'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'action.yml'
      - 'dist/**'

jobs:
  # test action works running from the graph
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        xcode-version: ["10.0", "10.3", "11.0", "11.5", "12.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: bot@sinoru.io
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
        env:
          SPACESHIP_SKIP_2FA_UPGRADE: 1
      - run: xcodebuild -version
